stages:
  - build
  - deploy

variables:
  NODE_VERSION: "18"

# Cache node_modules
cache:
  paths:
    - node_modules/

# Build stage
build:
  stage: build
  image: node:${NODE_VERSION}
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - .next/
      - public/
    expire_in: 1 hour
  only:
    - main
    - develop

# Deploy to Vercel
deploy:
  stage: deploy
  image: node:${NODE_VERSION}
  before_script:
    - npm install -g vercel@latest
  script:
    - echo "Deploying to Vercel..."
    - vercel --token $VERCEL_TOKEN --prod --yes
  environment:
    name: production
    url: https://$VERCEL_URL
  only:
    - main
  when: manual
  allow_failure: false

# Deploy to Vercel Preview
deploy-preview:
  stage: deploy
  image: node:${NODE_VERSION}
  before_script:
    - npm install -g vercel@latest
  script:
    - echo "Deploying preview to Vercel..."
    - vercel --token $VERCEL_TOKEN --yes
  environment:
    name: preview
    url: https://$VERCEL_PREVIEW_URL
  only:
    - develop
  when: manual
  allow_failure: true 